sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  global:
  - NODE_ENV=CI
stages:
  - install
  - test
  - name: build
  - if: branch = dev
  - name: deploy
    if: branch = dev

before_deploy:
  - openssl aes-256-cbc -K $encrypted_241975a5ee41_key -iv $encrypted_241975a5ee41_iv -in gce.json.enc -out gce.json -d
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file=gce.json
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components beta update
  - gcloud --quiet components update kubectl

jobs:
  include:
    - stage: install
      script:
        - npm install
    - stage: test
      script:
        - npm test
    - stage: build
      script:
        - docker build -t gcr.io/$GC_PROJECT_ID/brew-api:$TRAVIS_BUILD_NUMBER .
    - stage: deploy
      script:
        - gcloud auth configure-docker
        - docker push gcr.io/$GC_PROJECT_ID/brew-api:$TRAVIS_BUILD_NUMBER .
