sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  global:
  - NODE_ENV=CI
stages:
- install
- test
- build
- push
jobs:
  include:
  - stage: install
    script:
    - npm install
  - stage: test
    script:
    - npm run coveralls
  - stage: build
    script:
    - npm run build:prod
    - npm prune --production && npm install --production
    deploy:
      provider: gcs
      access_key_id: GOOG67BFJAKYDAHNSL2DUNX6
      secret_access_key:
        secure: NBvNrxoX5pTTfArh/JzB5liMaTep4YMrybwRq3hczmioPzbL8Tyt9BugSfTzjGcYDDkDQ/oWpHd6Ft84ZdR2alKuUW90xf0L3A3T4CH9LfAdE/e+hAOuWQnu7szZ7betVGvmDwkZzLjxyb57gTMF6NqYsVDyRmewMbyBxQhPtfdljULK/mdZH8XyS+X8YsiGIWVGtH/ZS6yqYPBKUEASVbqlIs3SEJtu0JZfTjFIlOB9VvnkKE9H+rHztPvL9GJlLB37z+PNzR2gUGxBUHrb+p95qNwIIXrhpwcaMSeKYkx3TGacmPhVqiQNvXO/lEyWCeW+OpcX1t15pkpVVMZlyO3sps39DJZr2flhRcUP17TMO1VLXrLbZvy1wzTHLQv78IthIL9iQlAfMzzoaiQeJChNSoCWfg4lnlx72agCGZiyihz9H4vdodcCXNpCtIJp2n2MyKdgwihTMNpIQO9SB5QI4r5BPrMmTexq1PGzOp/qyzE/dtQmeJK2/cyn54WqO3xLy0daFRfe1iEI+SmiOE6jCRX4ZRby0QTWpQym3m1Ig+ugOWwG6PuNQDLbl/Kt67mD+2SwpozaiNWFP5y/J0EsNMooLxyPVC5vzIEb0VAm2o02Iz6jysQTZEhg027YYYTL1A2Loe5/KyU/LN066oippFkbBvYVPpQdb3SnIis=
      bucket: personal-248114_travis
      local-dir: dist
      on:
        repo: dariusbakunas/brew-api
        branch: dev
  - stage: push
    script:
    - docker build -t travis-ci-build-stage -f Dockerfile.ci .
    - docker tag travis-ci-build-stage gcr.io/$GC_PROJECT_ID/brew-api:$TRAVIS_BUILD_NUMBER
    - openssl aes-256-cbc -K $encrypted_241975a5ee41_key -iv $encrypted_241975a5ee41_iv
      -in gce.json.enc -out gce.json -d
    - cat gce.json | docker login -u _json_key --password-stdin https://gcr.io
    - docker push gcr.io/$GC_PROJECT_ID/brew-api:$TRAVIS_BUILD_NUMBER
    if: "(branch = dev OR branch = master) AND type = push"
