sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/google-cloud-sdk/"
services:
- docker
env:
  global:
  - NODE_ENV=CI
before_install:
  - openssl aes-256-cbc -K $encrypted_241975a5ee41_key -iv $encrypted_241975a5ee41_iv
    -in gce.json.enc -out gce.json -d
install:
- npm install
script:
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- gcloud auth activate-service-account --key-file=gce.json
- npm test
before_deploy:
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export
  CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud --quiet version
- gcloud --quiet components update
- gcloud --quiet components beta update
- gcloud --quiet components update kubectl
