apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brew-api.fullname" . }}
  labels:
{{ include "brew-api.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "brew-api.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "brew-api.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health-check
              port: http
          readinessProbe:
            httpGet:
              path: /health-check
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PROD_DB_USERNAME
              value: {{ .Values.dbUsername }}
            - name: PROD_DB_NAME
              value: {{ .Values.dbName }}
            - name: PROD_DB_HOSTNAME
              value: {{ .Values.dbHostname }}
            - name: SENTRY_ENVIRONMENT
              value: {{ .Values.sentryEnvironment }}
            - name: LOG_LEVEL
              value: debug
            - name: PROD_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-api.name" . }}-secret
                  key: db-psw
            - name: SENDGRID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-api.name" . }}-secret
                  key: sendgrid-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "brew-api.name" . }}-secret
                  key: jwt-secret
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
