apiVersion: v1
kind: Secret
metadata:
  name: {{ include "brew-api.name" . }}-secret
  labels:
{{ include "brew-api.labels" . | indent 4 }}
type: Opaque
data:
  {{ if .Values.dbPassword }}
  db-psw: {{ .Values.dbPassword | b64enc | quote }}
  {{ else }}
  db-psw: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.sendgridKey }}
  sendgrid-key: {{ .Values.sendgridKey | b64enc | quote }}
  {{ else }}
  sendgrid-key: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}
  {{ if .Values.jwtSecret }}
  jwt-secret: {{ .Values.jwtSecret | b64enc | quote }}
  {{ else }}
  jwt-secret: {{ randAlphaNum 32 | b64enc | quote }}
  {{ end }}

